stages:
  - build
  - test
  - deploy

variables:
  ROBOT_SERVERS_IMAGE: "robotics-git.joanneum.at:4567/robo-gym/robot-servers/develop:latest"

before_script:
  # docker login asks for the password to be passed through stdin for security
  # we use $CI_JOB_TOKEN here which is a special token provided by GitLab
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

.build_robo-gym_image: &build_robo-gym_image_def
  image: docker:18.09
  services:
    - docker:18.09-dind
  tags:
    - docker-executor
  stage: build
  script:
    # fetch the latest image (not failing if image is not found)
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      --build-arg PYTHON_VER=$PYTHON_VER
      .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

build_robo-gym_image_py36:
  <<: *build_robo-gym_image_def
  variables:
      PYTHON_VER: "3.6"

echo_robot_server_image:
  stage: test
  script:
    - echo "$ROBOT_SERVERS_IMAGE"  
  

test_environments:
  image: docker:18.09
  before_script:
  - apk add docker-compose
  services:
    - docker:18.09-dind
  tags:
    - docker-executor
  stage: test
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA robo-gym
    - docker pull $ROBOT_SERVERS_IMAGE
    - docker tag $ROBOT_SERVERS_IMAGE robot-servers
    - docker-compose -f docker-compose-test-melodic.yml up -d
    - docker exec robo-gym pytest -x
    - docker-compose -f docker-compose-test-melodic.yml down
  except:
    - /^capsize.*$/
  
test_environments_with_master:
  image: docker:18.09
  before_script:
  - apk add docker-compose
  services:
    - docker:18.09-dind
  tags:
    - docker-executor
  stage: test
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull robotics-git.joanneum.at:4567/robo-gym/robot-servers/master:latest
    - docker tag robotics-git.joanneum.at:4567/robo-gym/robot-servers/master:latest robot-servers
    - docker-compose -f docker-compose-test-melodic.yml up -d
    - docker exec robo-gym pytest -x
    - docker-compose -f docker-compose-test-melodic.yml down
  only:
    - master

test_environments_with_rs_manual_deploy:
  image: docker:18.09
  before_script:
  - apk add docker-compose
  services:
    - docker:18.09-dind
  tags:
    - docker-executor
  stage: test
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull robotics-git.joanneum.at:4567/robo-gym/robot-servers/manual_deploy:latest
    - docker tag robotics-git.joanneum.at:4567/robo-gym/robot-servers/manual_deploy:latest robot-servers
    - docker-compose -f docker-compose-test-melodic.yml up -d
    - docker exec robo-gym pytest -x
    - docker-compose -f docker-compose-test-melodic.yml down
  when: manual

capsize_test_environments_with_rs_master:
  image: docker:18.09
  before_script:
  - apk add docker-compose
  services:
    - docker:18.09-dind
  tags:
    - docker-executor
  stage: test
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull robotics-git.joanneum.at:4567/robo-gym/robot-servers/capsize_master:latest
    - docker tag robotics-git.joanneum.at:4567/robo-gym/robot-servers/capsize_master:latest robot-servers
    - docker-compose -f docker-compose-test-melodic.yml up -d
    - docker exec robo-gym pytest -x
    - docker-compose -f docker-compose-test-melodic.yml down
  only:
    - /^capsize.*$/

capsize_test_environments_with_rs_develop:
  image: docker:18.09
  before_script:
  - apk add docker-compose
  services:
    - docker:18.09-dind
  tags:
    - docker-executor
  stage: test
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull robotics-git.joanneum.at:4567/robo-gym/robot-servers/capsize_develop:latest
    - docker tag robotics-git.joanneum.at:4567/robo-gym/robot-servers/capsize_develop:latest robot-servers
    - docker-compose -f docker-compose-test-melodic.yml up -d
    - docker exec robo-gym pytest -x
    - docker-compose -f docker-compose-test-melodic.yml down
  when: manual

deploy_production:
  image: python:3.6-slim-buster
  before_script:
     - pip3 install twine
     - python3 setup.py sdist
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
  only:
    - /^v*$/
  except:
    - branches
    - triggers
