stages:
  - build
  - deploy

variables:
  PYTHON_VER: "3.8"
  ROS_DISTRO: "noetic"
  ROBO_GYM_IMAGE: $CI_REGISTRY_IMAGE:$PYTHON_VER-$CI_COMMIT_SHA
  ROBOT_SERVERS_IMAGE: "$CI_REGISTRY/robo-gym/robot-servers:$ROS_DISTRO-develop-latest"  

before_script:
  # docker login asks for the password to be passed through stdin for security
  # we use $CI_JOB_TOKEN here which is a special token provided by GitLab
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

# The pipeline needs at minimum one job to run 
dummy:
  stage: build
  variables:
    GIT_STRATEGY: none
  script:
    - ":"
  only:
    - /^docs.*$/
    
.build_robo-gym_image: &build_robo-gym_image_def
  image: docker:18.09
  services:
    - docker:18.09-dind
  tags:
    - docker-executor
  stage: build
  retry:
    max: 2
  script:
    # fetch the latest image (not failing if image is not found)
    - docker pull $CI_REGISTRY_IMAGE:$PYTHON_VER-latest || true
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE:$PYTHON_VER-latest
      --tag $ROBO_GYM_IMAGE
      --build-arg PYTHON_VER=$PYTHON_VER
      --build-arg CACHEBUST=$CI_COMMIT_SHA
      .
    - docker push $ROBO_GYM_IMAGE
    - docker tag $ROBO_GYM_IMAGE $CI_REGISTRY_IMAGE:$PYTHON_VER-latest
    - docker push $CI_REGISTRY_IMAGE:$PYTHON_VER-latest
  except:
    - /^docs.*$/

build_robo-gym_image_py38:
  <<: *build_robo-gym_image_def
  variables:
      PYTHON_VER: "3.8"
  only:
    - schedules

build_robo-gym_image_py39:
  <<: *build_robo-gym_image_def
  variables:
      PYTHON_VER: "3.9"
  only:
    - schedules

deploy_docker_image: 
  image: docker:18.09
  services:
    - docker:18.09-dind
  tags:
    - docker-executor
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $ROBO_GYM_IMAGE
    - docker tag $ROBO_GYM_IMAGE $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:latest
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:latest
  only:
    - master 
    - develop
  except:
    - /^docs.*$/

deploy_production:
  image: python:3.8-slim-buster
  before_script:
     - pip3 install twine
     - python3 setup.py sdist
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
  only:
    - /^v.*$/
  except:
    refs:
      - branches
      - triggers
